# Generated by Django 2.2 on 2020-01-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("reminder_id", models.AutoField(primary_key=True, serialize=False)),
                ("zulip_user_id", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
