# Generated by Django 2.2 on 2020-01-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remindmoi_bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder", name="created", field=models.DateTimeField(),
        ),
    ]
